# Generated by Django 4.2.5 on 2023-09-21 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('severity', models.CharField(choices=[('S', 'Safe'), ('A', 'Alarm'), ('D', 'Danger')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('threshold_1', models.IntegerField()),
                ('threshold_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportMeasurementPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.measurementpoint')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
                ('x_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_reading', to='report.reading')),
                ('y_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y_reading', to='report.reading')),
                ('z_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='z_reading', to='report.reading')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='measurement_points',
            field=models.ManyToManyField(through='report.ReportMeasurementPoint', to='report.measurementpoint'),
        ),
        migrations.AddField(
            model_name='measurementpoint',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.standard'),
        ),
    ]
